import * as fs from 'fs'
import { AddressType, IPerson, MyInfoSource } from '../src/myinfo-types'

export const MOCK_BASE_URL = 'https://myinfo.gov.client'
export const MOCK_REDIRECT_PATH = '/target'
export const MOCK_TARGET_URL = `${MOCK_BASE_URL}${MOCK_REDIRECT_PATH}`
export const MOCK_CLIENT_ID = 'mockClientId'
export const MOCK_CLIENT_SECRET = 'mockClientSecret'
export const MOCK_ESRVC_ID = 'mockEsrvcId'
export const MOCK_PURPOSE = 'purpose'
export const MOCK_RELAY_STATE = 'relayState1,relayState2'
export const MOCK_REQUESTED_ATTRIBUTES = [
  'name' as const,
  'sex' as const,
  'mobileno' as const,
  'occupation' as const,
  'marital' as const,
]
export const MOCK_AUTH_CODE = 'mockAuthCode'
export const MOCK_ACCESS_TOKEN = 'mockAccessToken'
export const MOCK_UIN_FIN = 'mockUinFin'
export const MOCK_JWT = 'mockJwt'
export const TEST_SERVER_PORT = 5000
export const TEST_PRIVATE_KEY = fs.readFileSync(
  './node_modules/@opengovsg/mockpass/static/certs/key.pem',
)
export const TEST_PUBLIC_KEY = fs.readFileSync(
  './node_modules/@opengovsg/mockpass/static/certs/spcp.crt',
)

// Note that the MockPass data doesn't exactly conform to the IPerson
// interface followed by MyInfo, hence we do not assign the IPerson
// interface to this object
export const EXPECTED_PERSON_DATA = {
  uinfin: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: 'S9812390C',
  },
  name: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: 'GALVIN NG JIA SHENG',
  },
  hanyupinyinname: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: 'NG JIA SHENG',
  },
  aliasname: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: 'TIMOTHY GALVIN NG JIA SHENG',
  },
  hanyupinyinaliasname: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '',
  },
  marriedname: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '',
  },
  sex: {
    lastupdated: '2020-04-16',
    code: 'M',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'MALE',
  },
  race: {
    lastupdated: '2020-04-16',
    code: 'CN',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'CHINESE',
  },
  secondaryrace: {
    lastupdated: '2020-04-16',
    code: '',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: '',
  },
  dialect: {
    lastupdated: '2020-04-16',
    code: '',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: '',
  },
  nationality: {
    lastupdated: '2020-04-16',
    code: 'SG',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'SINGAPORE CITIZEN',
  },
  dob: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '1992-05-25',
  },
  birthcountry: {
    lastupdated: '2020-04-16',
    code: 'SG',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'SINGAPORE',
  },
  residentialstatus: {
    lastupdated: '2020-04-16',
    code: 'C',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'Citizen',
  },
  passportnumber: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: 'E43335677F',
  },
  passportexpirydate: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '2025-06-04',
  },
  regadd: {
    country: { code: 'SG', desc: 'SINGAPORE' },
    unit: { value: '192' },
    street: { value: 'TELOK BLANGAH STREET 31' },
    lastupdated: '2020-04-16',
    block: { value: '92A' },
    source: MyInfoSource.GovtVerified,
    postal: { value: '101092' },
    classification: 'C',
    floor: { value: '20' },
    type: AddressType.Singapore,
    building: { value: 'TELOK BLANGAH PARCVIEW' },
  },
  housingtype: {
    lastupdated: '2020-04-16',
    code: '',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: '',
  },
  hdbtype: {
    lastupdated: '2020-04-16',
    code: '',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: '',
  },
  hdbownership: [
    {
      termoflease: { value: 99 },
      dateofpurchase: { value: '2017-04-03' },
      leasecommencementdate: { value: '2019-04-20' },
      address: {
        country: { code: 'SG', desc: 'SINGAPORE' },
        unit: { value: '192' },
        street: { value: 'TELOK BLANGAH STREET 31' },
        block: { value: '92A' },
        postal: { value: '101092' },
        type: AddressType.Singapore,
        floor: { value: '20' },
        building: { value: 'TELOK BLANGAH PARCVIEW' },
      },
      balanceloanrepayment: { years: { value: 29 }, months: { value: 0 } },
      originalloanrepayment: { value: 30 },
      hdbtype: { code: '113', desc: '3-ROOM FLAT (HDB)' },
      source: MyInfoSource.GovtVerified,
      classification: 'C',
      monthlyloaninstalment: { value: 3000 },
      outstandingloanbalance: { value: 670000 },
      lastupdated: '2020-04-16',
      noofowners: { value: 0 },
      dateofownershiptransfer: { value: '' },
      loangranted: { value: 800000 },
    },
  ],
  ownerprivate: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: true,
  },
  email: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.UserProvided,
    classification: 'C',
    value: 'galvintesting@yahoo.com',
  },
  mobileno: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.UserProvided,
    classification: 'C',
    areacode: { value: '65' },
    prefix: { value: '+' },
    nbr: { value: '97399245' },
  },
  marital: {
    lastupdated: '2020-04-16',
    code: '3',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'WIDOWED',
  },
  marriagecertno: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '901889',
  },
  countryofmarriage: {
    lastupdated: '2020-04-16',
    code: 'SG',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    desc: 'SINGAPORE',
  },
  marriagedate: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '2012-02-15',
  },
  divorcedate: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    value: '',
  },
  childrenbirthrecords: [],
  sponsoredchildrenrecords: [],
  occupation: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.UserProvided,
    classification: 'C',
    value: 'TRAINING MANAGER',
  },
  employment: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.UserProvided,
    classification: 'C',
    value: 'BALIK KAMPUNG PTE LTD',
  },
  passtype: {
    lastupdated: '2020-04-16',
    code: '',
    source: MyInfoSource.NotApplicable,
    classification: 'C',
    desc: '',
  },
  passstatus: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.NotApplicable,
    classification: 'C',
    value: '',
  },
  passexpirydate: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.NotApplicable,
    classification: 'C',
    value: '',
  },
  employmentsector: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.NotApplicable,
    classification: 'C',
    value: '',
  },
  householdincome: {
    lastupdated: '2020-04-16',
    high: { value: 3999 },
    source: MyInfoSource.UserProvided,
    classification: 'C',
    low: { value: 3000 },
  },
  vehicles: [
    {
      roadtaxexpirydate: { value: '2020-03-23' },
      engineno: { value: '4F92AG9956' },
      attachment3: { value: 'ROOF TENT' },
      effectiveownership: { value: '2018-04-23T09:00:00' },
      scheme: { value: '' },
      powerrate: { value: 1.4 },
      source: MyInfoSource.GovtVerified,
      primarycolour: { value: 'BLACK' },
      type: { value: 'Motor Car' },
      vehicleno: { value: '' },
      coeexpirydate: { value: '2028-04-23' },
      chassisno: { value: 'FMEK3670WS013543' },
      noxemission: { value: 0.014321 },
      model: { value: 'AUDI R8' },
      openmarketvalue: { value: 34883.19 },
      coemission: { value: 0.187654 },
      attachment2: { value: 'BICYCLE CARRIER' },
      attachment1: { value: 'SUN ROOF' },
      make: { value: 'AUDI' },
      pmemission: { value: 0.188 },
      originalregistrationdate: { value: '2018-01-20' },
      yearofmanufacture: { value: '2018' },
      vpc: { value: '' },
      enginecapacity: { value: 5204 },
      classification: 'C',
      nooftransfers: { value: 1 },
      propellant: { value: 'Petrol' },
      co2emission: { value: 148 },
      motorno: { value: '' },
      minimumparfbenefit: { value: 2500 },
      thcemission: { value: 0.199887 },
      firstregistrationdate: { value: '2018-04-23' },
      lastupdated: '2020-04-16',
      maximumunladenweight: { value: 2000 },
      coecategory: { value: 'B - CAR ABOVE 1600CC OR 97KW' },
      maximumladenweight: { value: 2200 },
      secondarycolour: { value: '' },
      iulabelno: { value: '1221743695' },
      quotapremium: { value: 47402.23 },
      status: { code: '1', desc: 'LIVE' },
    },
  ],
  drivinglicence: {
    revocation: { startdate: { value: '' }, enddate: { value: '' } },
    totaldemeritpoints: { value: 0 },
    disqualification: { startdate: { value: '' }, enddate: { value: '' } },
    qdl: {
      expirydate: { value: '' },
      validity: { code: 'V', desc: 'VALID' },
      classes: [{ class: { value: '3' }, issuedate: { value: '2010-07-07' } }],
    },
    lastupdated: '2020-04-16',
    pdl: {
      expirydate: { value: '' },
      validity: { code: '', desc: '' },
      classes: [],
    },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    comstatus: { code: 'Y', desc: 'Eligible' },
    photocardserialno: { value: '93459632' },
    suspension: { startdate: { value: '' }, enddate: { value: '' } },
  },
  merdekagen: {
    lastupdated: '2020-04-16',
    eligibility: { value: '' },
    quantum: { value: '' },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    message: { code: '', desc: '' },
  },
  silversupport: {
    lastupdated: '2020-04-16',
    eligibility: { value: '' },
    amount: { value: '' },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    year: { value: '' },
  },
  gstvoucher: {
    gstregular: { value: 0 },
    year: { value: '' },
    lastupdated: '2020-04-16',
    exclusion: { value: '' },
    gstmedisave: { value: 0 },
    gstspecial: { value: 0 },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    signup: { value: '' },
  },
  'noa-basic': {
    yearofassessment: { value: '2019' },
    lastupdated: '2020-04-16',
    amount: { value: 54000 },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
  },
  noa: {
    amount: { value: 54000 },
    trade: { value: 0 },
    interest: { value: 0 },
    yearofassessment: { value: '2019' },
    taxclearance: { value: 'N' },
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    employment: { value: 54000 },
    classification: 'C',
    rent: { value: 0 },
    category: { value: 'ORIGINAL' },
  },
  'noahistory-basic': {
    noas: [
      { yearofassessment: { value: '2019' }, amount: { value: 54000 } },
      { yearofassessment: { value: '2018' }, amount: { value: 49200 } },
    ],
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
  },
  noahistory: {
    noas: [
      {
        amount: { value: 54000 },
        trade: { value: 0 },
        interest: { value: 0 },
        yearofassessment: { value: '2019' },
        taxclearance: { value: 'N' },
        employment: { value: 54000 },
        rent: { value: 0 },
        category: { value: 'ORIGINAL' },
      },
      {
        amount: { value: 49200 },
        trade: { value: 0 },
        interest: { value: 0 },
        yearofassessment: { value: '2018' },
        taxclearance: { value: 'N' },
        employment: { value: 49200 },
        rent: { value: 0 },
        category: { value: 'ORIGINAL' },
      },
    ],
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    classification: 'C',
  },
  cpfcontributions: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    history: [
      {
        date: { value: '2019-04-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 2475 },
        month: { value: '2019-04' },
      },
      {
        date: { value: '2019-05-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1237.5 },
        month: { value: '2019-05' },
      },
      {
        date: { value: '2019-06-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1237.5 },
        month: { value: '2019-06' },
      },
      {
        date: { value: '2019-07-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1237.5 },
        month: { value: '2019-07' },
      },
      {
        date: { value: '2019-08-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 3712.5 },
        month: { value: '2019-08' },
      },
      {
        date: { value: '2019-09-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2019-09' },
      },
      {
        date: { value: '2019-10-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2019-10' },
      },
      {
        date: { value: '2019-11-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2019-11' },
      },
      {
        date: { value: '2019-12-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2019-12' },
      },
      {
        date: { value: '2020-01-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2020-01' },
      },
      {
        date: { value: '2020-02-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2020-02' },
      },
      {
        date: { value: '2020-03-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 1425 },
        month: { value: '2020-03' },
      },
      {
        date: { value: '2020-04-15' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
        amount: { value: 2850 },
        month: { value: '2020-04' },
      },
    ],
    classification: 'C',
  },
  cpfemployers: {
    lastupdated: '2020-04-16',
    source: MyInfoSource.GovtVerified,
    history: [
      {
        month: { value: '2019-04' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-05' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-06' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-07' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-08' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-09' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-10' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-11' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2019-12' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2020-01' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2020-02' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2020-03' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
      {
        month: { value: '2020-04' },
        employer: { value: 'BALIK KAMPUNG PTE LTD' },
      },
    ],
    classification: 'C',
  },
  cpfbalances: {
    lastupdated: '2020-04-16',
    oa: { value: 49602.38 },
    source: MyInfoSource.GovtVerified,
    classification: 'C',
    ma: { value: 17253 },
    sa: { value: 12939.75 },
  },
}
